services:
  datenatlas_zivilgesellschaft_mcp:
    build: .
    image: datenatlas-zivilgesellschaft-mcp:local
    volumes:
      - ./:/app
    ports:
      - "8011:8011"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PIVEAU_SEARCH_BASE_URL=${PIVEAU_SEARCH_BASE_URL:-https://piveau-search.datenkatalog.datenatlas-zivilgesellschaft.de}
    restart: unless-stopped
